[build]
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/ps/*"
  status = 200
  force = true
  conditions = {Role = ["pro"]}

[[redirects]]
  from = "/ps/*"
  to = "/.netlify/functions/redirect"
  status = 200
  force = true
